import { Grid } from "@mui/material";
import { Inter } from "@next/font/google";
import Head from "next/head";
import Link from "next/link";
import MainBox from "../components/main_box";
import styles from "../styles/Home.module.css";
import { getRandomColor } from "../utils/utils";

const inter = Inter({ subsets: ["latin"] });
export default function Home({ pokemons }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container rowSpacing={{ xs: 2, md: 4 }} columnSpacing={4}>
          {pokemons.map((pokeData) => {
            return (
              <Grid item xs={6} md={12} key={pokeData.id}>
                <Link href={`/pokemon/${pokeData.id}`}>
                  <MainBox pokeData={pokeData}></MainBox>
                </Link>
              </Grid>
            );
          })}
        </Grid>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=100");
  const data = await res.json();
  if (!data) {
    return;
    ("Pokemon not found");
  }

  let pokemons = [];
  for (let i = 0; i < data.results.length; i++) {
    pokemons.push({
      id: i + 1,
      imgSrc: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${
        i + 1
      }.png`,
      pokeName: data.results[i].name,
      bgColor: getRandomColor(),
    });
  }

  return {
    props: {
      pokemons,
    },
  };
}
